# Generated by Django 6.1.1 on 2026-10-05 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TherapeuticRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título de la Receta')),
                ('summary', models.TextField(verbose_name='Descripción Apetecible')),
                ('category', models.CharField(default='Almuerzo / Cena', max_length=100, verbose_name='Categoría (Desayuno, Almuerzo, Snack)')),
                ('prep_time_minutes', models.PositiveIntegerField(default=25, verbose_name='Tiempo de Preparación (min)')),
                ('servings', models.PositiveIntegerField(default=4, verbose_name='Porciones Familiares')),
                ('difficulty', models.CharField(choices=[('FACIL', 'Fácil (Menos de 20 min)'), ('MEDIA', 'Media (20 a 45 min)'), ('ELABORADA', 'Elaborada (Fin de semana)')], default='FACIL', max_length=15, verbose_name='Dificultad')),
                ('is_kid_approved', models.BooleanField(default=True, verbose_name='Aprobada por Niños / Sabor Familiar')),
                ('ingredients_list', models.JSONField(default=list, verbose_name='Lista de Ingredientes y Cantidades')),
                ('instructions_steps', models.JSONField(default=list, verbose_name='Paso a Paso de Preparación')),
                ('hepatic_benefits', models.TextField(help_text='Por qué esta receta es anti-esteatosis (colina, antioxidantes, fibra, etc.)', verbose_name='Beneficio Clínico para el Hígado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Receta Terapéutica',
                'verbose_name_plural': 'Recetas Terapéuticas',
                'ordering': ['-created_at'],
            },
        ),
    ]
