# Generated by Django 6.1.1 on 2026-10-05 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Código de Barras EAN/UPC')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre del Producto')),
                ('brand', models.CharField(blank=True, max_length=100, verbose_name='Marca')),
                ('category', models.CharField(default='General', max_length=100, verbose_name='Categoría')),
                ('traffic_light', models.CharField(choices=[('GREEN', '🟢 Apto & Seguro'), ('YELLOW', '🟡 Consumo con Moderación'), ('RED', '🔴 Alerta Hepática (Fructosa / Ultraprocesado)')], default='GREEN', max_length=10, verbose_name='Semáforo Hepático')),
                ('ingredients_raw', models.TextField(verbose_name='Lista Completa de Ingredientes')),
                ('detected_harmful_ingredients', models.JSONField(blank=True, default=list, verbose_name='Ingredientes de Riesgo Detectados')),
                ('suggested_swap_product', models.CharField(blank=True, max_length=200, verbose_name='Cambio Seguro (Producto Sustituto)')),
                ('swap_reasoning', models.TextField(blank=True, verbose_name='Explicación del Cambio Culinario')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Alimento Analizado',
                'verbose_name_plural': 'Alimentos Analizados',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Nombre del Ingrediente')),
                ('aliases', models.TextField(blank=True, help_text='Separados por comas. Ej: JMAF, jarabe de maíz alto en fructosa, HFCS-55, isoglucosa', verbose_name='Sinónimos y Nombres Comerciales')),
                ('is_hidden_fructose', models.BooleanField(default=False, verbose_name='¿Es Fructosa Oculta o Derivado?')),
                ('risk_level', models.CharField(choices=[('GREEN', 'Seguro / Protector Hepático'), ('YELLOW', 'Precaución / Consumo Moderado'), ('RED', 'Alerta Hepática / Prohibido en MASLD')], default='GREEN', max_length=10, verbose_name='Nivel de Riesgo Hepático')),
                ('clinical_mechanism', models.TextField(blank=True, help_text='Por qué afecta o beneficia al hígado (ej. estimula lipogénesis de novo)', verbose_name='Mecanismo Fisiopatológico')),
                ('suggested_alternative', models.CharField(blank=True, max_length=200, verbose_name='Alternativa Saludable Segura')),
            ],
            options={
                'verbose_name': 'Ingrediente Clínico',
                'verbose_name_plural': 'Ingredientes Clínicos',
                'ordering': ['name'],
            },
        ),
    ]
