# Generated by Django 6.1.1 on 2026-10-05 22:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetabolicLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Fecha de Toma de Muestra / Control')),
                ('alt_tgp', models.FloatField(blank=True, help_text='Alanina Aminotransferasa. Normal óptimo: <25-30 U/L', null=True, verbose_name='ALT / TGP (U/L)')),
                ('ast_tgo', models.FloatField(blank=True, help_text='Aspartato Aminotransferasa. Normal óptimo: <35 U/L', null=True, verbose_name='AST / TGO (U/L)')),
                ('ggt', models.FloatField(blank=True, help_text='Gamma-Glutamil Transferasa. Normal: <30-50 U/L', null=True, verbose_name='GGT (U/L)')),
                ('weight_kg', models.FloatField(blank=True, null=True, verbose_name='Peso (kg)')),
                ('height_cm', models.FloatField(blank=True, null=True, verbose_name='Estatura (cm)')),
                ('dietary_adherence_percent', models.IntegerField(default=100, help_text='Estimación de cumplimiento de dieta baja en fructosa', verbose_name='Adherencia a Dieta (%)')),
                ('ultrasound_findings', models.TextField(blank=True, verbose_name='Hallazgos Ecográficos / FibroScan')),
                ('notes', models.TextField(blank=True, verbose_name='Observaciones Clínicas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metabolic_logs', to='patients.patient', verbose_name='Paciente')),
            ],
            options={
                'verbose_name': 'Registro Metabólico',
                'verbose_name_plural': 'Registros Metabólicos',
                'ordering': ['-date'],
            },
        ),
    ]
