# Generated by Django 6.1.1 on 2026-10-05 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre Completo')),
                ('birth_date', models.DateField(verbose_name='Fecha de Nacimiento')),
                ('gender', models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino'), ('O', 'Otro')], default='F', max_length=1, verbose_name='Sexo')),
                ('diagnosis', models.CharField(default='Hígado Graso Metabólico (MASLD)', max_length=200, verbose_name='Diagnóstico Principal')),
                ('severity_stage', models.CharField(choices=[('EVAL', 'En Evaluación Clínica'), ('GRADE_1', 'Grado 1 — Esteatosis Leve (<33% grasa)'), ('GRADE_2', 'Grado 2 — Esteatosis Moderada (33-66% grasa)'), ('GRADE_3', 'Grado 3 — Esteatosis Severa (>66% grasa)'), ('REVERSED', 'En Remisión / Valores Normalizados')], default='GRADE_1', max_length=20, verbose_name='Estadio Clínico')),
                ('guardian_contact', models.CharField(blank=True, max_length=150, verbose_name='Contacto Apoderado / Padre')),
                ('clinical_notes', models.TextField(blank=True, verbose_name='Notas Clínicas & Pautas del Nutricionista')),
                ('is_active', models.BooleanField(default=True, verbose_name='Expediente Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Modificación')),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
                'ordering': ['-created_at'],
            },
        ),
    ]
